// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DarkModeController from "./dark_mode_controller.js"
application.register("dark-mode", DarkModeController)

import DatepickerController from "./datepicker_controller.js"
application.register("datepicker", DatepickerController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import Select2Controller from "./select2_controller.js"
application.register("select2", Select2Controller)

import SidebarController from "./sidebar_controller.js"
application.register("sidebar", SidebarController)
